package by.nosevich.courses.test.exception;

public class UserGettingException extends Exception {

    public UserGettingException(Throwable cause) {
        super(cause);
    }
}
