package by.nosevich.courses.test.exception;

public class UserSavingException extends Exception {
    public UserSavingException(Throwable cause) {
        super(cause);
    }
}
